In [1]:
import pandas as pd
df1= pd.read_excel('C:\\Users\\Lenovo\\Downloads\\Documents\\ecom data reduced (2).xlsx')

In [2]:
df1['COMMENTS']

0        Great CD: My lovely Pat has one of the GREAT ...
1        One of the best game music soundtracks - for ...
2        Batteries died within a year ...: I bought th...
3        works fine, but Maha Energy is better: Check ...
4        Great for the non-audiophile: Reviewed quite ...
                              ...                        
7967     A wonderful mistery book: I love it. I'm a fa...
7968     PRINT WAY, WAY TOO SMALL!!: All the stories o...
7969     Classic is a classic: Sherlock is a classic. ...
7970     VERY Small Type Makes Reading Difficult (Impo...
7971     The Author Has An Odd Fascination: I read thi...
Name: COMMENTS, Length: 7972, dtype: object

In [7]:
# lets bring entire document to lower case

In [8]:
df1["COMMENTS"]=df1["COMMENTS"].apply(lambda x:" ".join(x.lower() for x in str(x).split()))

In [9]:
df1["COMMENTS"]

0       great cd: my lovely pat has one of the great v...
1       one of the best game music soundtracks - for a...
2       batteries died within a year ...: i bought thi...
3       works fine, but maha energy is better: check o...
4       great for the non-audiophile: reviewed quite a...
                              ...                        
7967    a wonderful mistery book: i love it. i'm a fan...
7968    print way, way too small!!: all the stories of...
7969    classic is a classic: sherlock is a classic. a...
7970    very small type makes reading difficult (impos...
7971    the author has an odd fascination: i read this...
Name: COMMENTS, Length: 7972, dtype: object

In [10]:
# Now we will remove all puncuations from the document

In [11]:
df1["COMMENTS"]=df1["COMMENTS"].str.replace('[^\w\s]','')

In [12]:
df1["COMMENTS"]

0       great cd my lovely pat has one of the great vo...
1       one of the best game music soundtracks  for a ...
2       batteries died within a year  i bought this ch...
3       works fine but maha energy is better check out...
4       great for the nonaudiophile reviewed quite a b...
                              ...                        
7967    a wonderful mistery book i love it im a fan of...
7968    print way way too small all the stories of she...
7969    classic is a classic sherlock is a classic and...
7970    very small type makes reading difficult imposs...
7971    the author has an odd fascination i read this ...
Name: COMMENTS, Length: 7972, dtype: object

In [13]:
# Now we will remove all digits/numbers from the document

In [14]:
df1["COMMENTS"]=df1["COMMENTS"].str.replace('\d+','')

In [15]:
df1["COMMENTS"]

0       great cd my lovely pat has one of the great vo...
1       one of the best game music soundtracks  for a ...
2       batteries died within a year  i bought this ch...
3       works fine but maha energy is better check out...
4       great for the nonaudiophile reviewed quite a b...
                              ...                        
7967    a wonderful mistery book i love it im a fan of...
7968    print way way too small all the stories of she...
7969    classic is a classic sherlock is a classic and...
7970    very small type makes reading difficult imposs...
7971    the author has an odd fascination i read this ...
Name: COMMENTS, Length: 7972, dtype: object

In [16]:
# Now we have to remove stop words

In [17]:
# Improting stop words directory

In [18]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [19]:
# Incase you see error 'stopwords not found' run below command and re-run above command

In [20]:
import nltk
nltk.download()
nltk.download('stopwords')

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [21]:
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [22]:
# in case we want to add to the list of stopwords, eg your company name. use this command 

In [23]:
stop.append('Protouch')

In [24]:
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [25]:
# in case we want to remove to the list of stopwords, eg your company name. use this command 

In [26]:
stop.remove('Protouch')

In [27]:
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [28]:
# Now we will remove the stopwords from the documents

In [29]:
df1['COMMENTS']=df1['COMMENTS'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [30]:
df1['COMMENTS']

0       great cd lovely pat one great voices generatio...
1       one best game music soundtracks game didnt rea...
2       batteries died within year bought charger jul ...
3       works fine maha energy better check maha energ...
4       great nonaudiophile reviewed quite bit combo p...
                              ...                        
7967    wonderful mistery book love im fan sherlock st...
7968    print way way small stories sherlock holmes cr...
7969    classic classic sherlock classic go along hyst...
7970    small type makes reading difficult impossible ...
7971    author odd fascination read book law school au...
Name: COMMENTS, Length: 7972, dtype: object

In [31]:
# Now we will be stemming the data

In [32]:
from nltk.stem import PorterStemmer
st=PorterStemmer()
df1['COMMENTS'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

0       great cd love pat one great voic gener listen ...
1       one best game music soundtrack game didnt real...
2       batteri die within year bought charger jul wor...
3       work fine maha energi better check maha energi...
4       great nonaudiophil review quit bit combo playe...
                              ...                        
7967    wonder misteri book love im fan sherlock stori...
7968    print way way small stori sherlock holm cram o...
7969    classic classic sherlock classic go along hyst...
7970    small type make read difficult imposs typefac ...
7971    author odd fascin read book law school author ...
Name: COMMENTS, Length: 7972, dtype: object

In [33]:
# Now we will work on Bag of Words

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

In [35]:
cv=CountVectorizer()
x = cv.fit_transform(df1['COMMENTS']).toarray()

In [36]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
x.shape

(7972, 35983)

In [38]:
import numpy
numpy.savetxt("trial112.csv", x, delimiter=",")

In [39]:
df3 = cv.get_feature_names()

In [40]:
df3

['aa',
 'aaa',
 'aaagggghhhhhhh',
 'aaahhhh',
 'aaarrrggghhh',
 'aacsrunning',
 'aages',
 'aahhh',
 'aaiwtlg',
 'aalfred',
 'aap',
 'aardvark',
 'aaron',
 'aarons',
 'aaspect',
 'ab',
 'aback',
 'abandod',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonnes',
 'abandons',
 'abarca',
 'abb',
 'abberation',
 'abbey',
 'abbeys',
 'abbott',
 'abbreviated',
 'abbreviation',
 'abby',
 'abckand',
 'abdomial',
 'abdominal',
 'abducted',
 'abduction',
 'abductions',
 'abel',
 'abendroth',
 'abercrombie',
 'aberdeen',
 'abetter',
 'abhor',
 'abide',
 'abilities',
 'ability',
 'abit',
 'abject',
 'able',
 'ablity',
 'aboard',
 'abolish',
 'abominable',
 'abomination',
 'abominations',
 'abook',
 'aboration',
 'aboriginal',
 'aborted',
 'abortion',
 'abortions',
 'abot',
 'abound',
 'abounds',
 'aboundthe',
 'aboutadifferent',
 'aboutalso',
 'abouti',
 'aboutmarquez',
 'aboutthe',
 'abovementioned',
 'abraham',
 'abrahams',
 'abrasive',
 'abreviated',
 'abridge',
 'abridged',
 'abridgedaudiobook

In [41]:
df4=pd.DataFrame(df3)
df4.to_csv('trail113.csv',index=False)

In [42]:
# Now lets get the polarity for each comment line

In [43]:
y = df1['Polarity']
y

0       1
1       1
2       0
3       1
4       1
       ..
7967    0
7968    1
7969    0
7970    0
7971    0
Name: Polarity, Length: 7972, dtype: int64

In [44]:
# Now we will split the data set into test and train

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.20, random_state=0)

In [46]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
y_train

675     0
402     1
7591    0
1917    1
1150    1
       ..
4931    1
3264    1
1653    0
2607    0
2732    0
Name: Polarity, Length: 6377, dtype: int64

In [49]:
y_test

6946    0
5356    0
521     0
5900    1
6955    1
       ..
5739    0
6603    1
4761    0
597     0
826     0
Name: Polarity, Length: 1595, dtype: int64

In [50]:
X_train.shape

(6377, 35983)

In [51]:
X_test.shape

(1595, 35983)

In [52]:
# Now we will start logistic regression on the train data

In [53]:
from sklearn.linear_model import LogisticRegression
YHAT=LogisticRegression()
YHAT.fit(X_train,y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [57]:
# Since we have very high number of words, we will have a look at some of them

In [58]:
# This is a readymade syntex for printing top 25 rows for +ve and -ve polarity

In [59]:
# in case you want to change the number of 25 to a different number, change n=25

In [60]:
# Once you see this out, please varify broadly -ve and +ve are correct, else interchage 'positive' and 'negative' in the below syntex

In [61]:
def show_most_informative_features(vectorizer, YHAT, n=25):
    d = {}
    a=0
    feature_names = vectorizer.get_feature_names()
    coefs_with_fns = sorted(zip(YHAT.coef_[0], feature_names))
    top = zip(coefs_with_fns[:n], coefs_with_fns[:-(n + 1):-1])
    print("\t\t\tNegative\t\t\t\t\t\tPositive")
    print("________________________________________________________________________________________________")
    for (coef_1, fn_1), (coef_2, fn_2) in top:
        print("\t%.4f\t%-15s\t\t\t\t%.4f\t%-15s" % (coef_1, fn_1, coef_2, fn_2))
        d[a]=fn_1
        a+=1
    
show_most_informative_features(cv,YHAT)

			Negative						Positive
________________________________________________________________________________________________
	-1.2351	commentary     				1.4079	missed         
	-1.2097	except         				1.1081	shots          
	-1.1564	realism        				1.0895	clarity        
	-1.1365	storage        				1.0655	wash           
	-1.1176	college        				1.0158	collect        
	-1.1137	maps           				1.0069	metal          
	-1.1119	imagination    				0.9849	toes           
	-1.1114	fish           				0.9774	classes        
	-1.1015	happening      				0.9730	office         
	-1.0967	instructions   				0.9568	smaller        
	-1.0660	readers        				0.9551	needless       
	-1.0596	deeper         				0.9521	itll           
	-1.0594	positive       				0.9480	joe            
	-1.0540	package        				0.9411	five           
	-1.0364	pair           				0.9295	board          
	-1.0180	annoying       				0.9264	machine        
	-1.0148	mustsee        				0.9149	humorous       
	-0.9866	v

In [62]:
# Now we will test the model on test data

In [63]:
y_pred = YHAT.predict(X_test)

In [64]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [65]:
# we can optically see the accuracy of few outputs of y_pred vs y-test

In [66]:
y_test

6946    0
5356    0
521     0
5900    1
6955    1
       ..
5739    0
6603    1
4761    0
597     0
826     0
Name: Polarity, Length: 1595, dtype: int64

In [67]:
# We can run this syntex to check the accuracy of the model. Note the accuracy

In [68]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.54      0.52      0.53       807
           1       0.52      0.54      0.53       788

    accuracy                           0.53      1595
   macro avg       0.53      0.53      0.53      1595
weighted avg       0.53      0.53      0.53      1595

